config/routes.rb
Rails.application.routes.draw do

  resources :tagged_skills,    :only => [:create, :destroy, :publish_skill, :hide_skill]
  resources :skill_plus,       :only => [:create, :destroy]
  resources :skills,           :only => [:index, :show, :create]
  resources :users            

  root 'application#root'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'publish_skill'  => 'tagged_skills#publish_skill'
  post   'hide_skill'     => 'tagged_skills#hide_skill'

end

app/models/skill_plu.rb
class SkillPlu < ActiveRecord::Base
  belongs_to :tagged_user, class_name: "User"
  belongs_to :by_user,     class_name: "User"
  belongs_to :skill, 	  class_name: "Skill"
  
  validates :tagged_user, presence: true
  validates :by_user, presence: true
  validates :skill, presence: true
end

app/controllers/skill_plus_controller.rb
class SkillPlusController < ApplicationController
  include SkillPlusHelper
  before_action :set_skill_plu, only: [:show, :edit, :update, :destroy]

  # GET /skill_plus
  # GET /skill_plus.json
  def index
    @skill_plus = SkillPlu.all
  end

  # GET /skill_plus/1
  # GET /skill_plus/1.json
  def show
  end

  # GET /skill_plus/new
  def new
    @skill_plu = SkillPlu.new
  end

  # GET /skill_plus/1/edit
  def edit
  end

  # POST /skill_plus
  # POST /skill_plus.json
  def create
    if params[:tagged_user_id] == params[:by_user_id]
      redirect_to :back
      return
    end
    if not is_plused?(*skill_plu_params)
      @skill_plu = SkillPlu.create(skill_plu_params)
    end
    redirect_to :back
  end

  # PATCH/PUT /skill_plus/1
  # PATCH/PUT /skill_plus/1.json
  def update
    respond_to do |format|
      if @skill_plu.update(skill_plu_params)
        format.html { redirect_to @skill_plu, notice: 'Skill plu was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_plu }
      else
        format.html { render :edit }
        format.json { render json: @skill_plu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_plus/1
  # DELETE /skill_plus/1.json
  def destroy
    @skill_plu.destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_plu
      @skill_plu = SkillPlu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_plu_params
      params.permit(:skill_id, :tagged_user_id, :by_user_id)
    end
end

app/helpers/skill_plus_helper.rb
module SkillPlusHelper
  def is_plused?(skill_id, tagged_user_id, by_user_id)
    not SkillPlu.find_by(by_user_id: by_user_id, tagged_user_id: tagged_user_id, skill_id: skill_id).nil?
  end
end

app/views/skill_plus/_form.html.erb
<%= form_for(@skill_plu) do |f| %>
  <% if @skill_plu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_plu.errors.count, "error") %> prohibited this skill_plu from being saved:</h2>

      <ul>
      <% @skill_plu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill_id %><br>
    <%= f.number_field :skill_id %>
  </div>
  <div class="field">
    <%= f.label :tagged_user_id %><br>
    <%= f.number_field :tagged_user_id %>
  </div>
  <div class="field">
    <%= f.label :by_user_id %><br>
    <%= f.number_field :by_user_id %>
  </div>
  <div class="actions">
    <%= f.submit("", :class => "btn") %>
  </div>
<% end %>

app/views/skill_plus/edit.html.erb
<h1>Editing Skill Plu</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_plu %> |
<%= link_to 'Back', skill_plus_path %>

app/views/skill_plus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skill Plus</h1>

<table>
  <thead>
    <tr>
      <th>Skill</th>
      <th>Tagged user</th>
      <th>By user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_plus.each do |skill_plu| %>
      <tr>
        <td><%= skill_plu.skill_id %></td>
        <td><%= skill_plu.tagged_user_id %></td>
        <td><%= skill_plu.by_user_id %></td>
        <td><%= link_to 'Show', skill_plu %></td>
        <td><%= link_to 'Edit', edit_skill_plu_path(skill_plu) %></td>
        <td><%= link_to 'Destroy', skill_plu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill plu', new_skill_plu_path %>

app/views/skill_plus/new.html.erb
<h1>New Skill Plu</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_plus_path %>

app/views/skill_plus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skill:</strong>
  <%= @skill_plu.skill_id %>
</p>

<p>
  <strong>Tagged user:</strong>
  <%= @skill_plu.tagged_user_id %>
</p>

<p>
  <strong>By user:</strong>
  <%= @skill_plu.by_user_id %>
</p>

<%= link_to 'Edit', edit_skill_plu_path(@skill_plu) %> |
<%= link_to 'Back', skill_plus_path %>