config/routes.rb
Rails.application.routes.draw do

  resources :tagged_skills,    :only => [:create, :destroy, :publish_skill, :hide_skill]
  resources :skill_plus,       :only => [:create, :destroy]
  resources :skills,           :only => [:index, :show, :create]
  resources :users            

  root 'application#root'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'publish_skill'  => 'tagged_skills#publish_skill'
  post   'hide_skill'     => 'tagged_skills#hide_skill'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :active_skill_plus,
		class_name: "SkillPlu",
		foreign_key: "by_user_id",
		dependent: :destroy
	has_many :passive_skill_plus,
		class_name: "SkillPlu",
		foreign_key: "tagged_user_id",
		dependent: :destroy

	has_many :tagged_skills,
		class_name: "TaggedSkill",
		foreign_key: "user_id",
		dependent: :destroy

	has_many :plus_skills,
		through: :passive_skill_plus,
		source: :skill
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @is_me = current_user == @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def get_skill_counts(user, state="public")
		# skill id, user id ,state
		tss = user.tagged_skills.where(state: state)  
		# skill id, user id(tagged), user id(who plussed)
		psps = user.passive_skill_plus.select("id, tagged_user_id, by_user_id AS byu, skill_id AS skid")
		psps = tss.joins("LEFT JOIN (#{psps.to_sql}) AS X ON user_id = tagged_user_id AND tagged_skills.\"skill_id\" = skid") 
		# skill id, count
		psps = psps.select('tagged_skills."skill_id", COUNT(byu) AS cnt')
			.group('tagged_skills."skill_id"') 
		# skill id, count, skill name
		psps = ActiveRecord::Base.connection.select_all(
			"SELECT skill_id, cnt, name
				FROM (#{psps.to_sql}) AS Y LEFT JOIN skills ON skill_id = skills.id")
		tss = psps.map{|x| x["skill_id"]} 
		counts = psps.map{|x| x["cnt"]}
		skill_names = psps.map{|x| x["name"]}
		counts = tss.zip(counts, skill_names).sort{|a, b| b[1] <=> a[1]}
	end


	def get_plussed_skills(curren_user, user, counts)
		plussed_skills = current_user.active_skill_plus
		    .where("by_user_id = ? AND tagged_user_id = ? AND skill_id IN (?) ",
		      current_user.id, user.id, counts.map{|count| count[0]})
		    .joins("LEFT JOIN skills ON skill_plus.skill_id = skills.id")
		    .select("skill_plus.id, skills.id AS sid, skills.name AS sname")
	end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit(:class => "btn")%>
  </div>
<% end %>

app/views/users/_skill_counts.html.erb
<table class="table">
  <% counts.each do |count| %>
    <% skill_id, cnt, skill_name = count[0].to_i, count[1], count[2] %>
    <% sidi = skill_ids.index(skill_id) %>
    <tr><td>
      <%= link_to(skill_name, "/skills/" + skill_id.to_s) %>:

      <% if not sidi.nil? %>
        <%# form_params = [skill_plus_path + "/" + sidi.to_s, html: {method: :delete }] %>
        <% form_params = [skill_plus_path + "/" + plussed_skills[sidi].id.to_s,
          :method => :delete ] %>
        <% s = "plussed_skill" %>
      <% else %>
        <% form_params = [current_user.active_skill_plus.build] %>
        <% s = "unplussed_skill" %>
      <% end %>

      <%= form_tag(*form_params)  do |f| %>
        <div> <%= hidden_field_tag :by_user_id, current_user.id %> </div>
        <div> <%= hidden_field_tag :tagged_user_id, user.id %> </div>
        <div> <%= hidden_field_tag :skill_id, skill_id %> </div>
        <%= submit_tag(cnt.to_s, :class => "btn #{s}", :disabled => @is_me)  %>
      <% end %>
      
      <% if @is_me %>
        <% if state == "public" %>
          <%= button_to "hide",
            {controller: 'tagged_skills', action: 'hide_skill',
            user_id: user.id, skill_id: skill_id}, {:remote => true, :class => "btn"} %>
        <% else %>
          <%= button_to "publish",
            {controller: 'tagged_skills', action: 'publish_skill',
            user_id: user.id, skill_id: skill_id}, {:remote => true, :class => "btn"} %>
        <% end %>
      <% end %>
    </td></tr>
  <% end %>
</table>

app/views/users/_tagged_skills.html.erb
<div class="tagged_skills">
  <% counts = get_skill_counts(user) %>
  <% if current_user.nil? %>
    <table class="table">
      <% counts.each do |count| %>
        <tr><td>
          <% skill_id, cnt, skill_name = count[0], count[1], count[2] %>
            <%= link_to(skill_name, "/skills/" + skill_id.to_s) %>:
            <%= cnt %>
        </td></tr>
      <% end %>
    </table>

  <% else %> 
    <% plussed_skills = get_plussed_skills(current_user, user, counts) %>
    <% skill_ids = plussed_skills.map(&:sid) %>
    <%= render "skill_counts",
      counts: counts, skill_ids: skill_ids,  plussed_skills: plussed_skills,
      user: user, state: "public" %>
    <%= render "tagged_skills/form", user: user%>

    <% if @is_me %>
      <h3>private skills</h3>
      <% counts = get_skill_counts(current_user, state="private") %>
      <% plussed_skills = get_plussed_skills(current_user, user, counts) %>
      <% skill_ids = plussed_skills.map(&:sid) %>
      <%= render "skill_counts",
        counts: counts, skill_ids: skill_ids,  plussed_skills: plussed_skills,
        user: user, state: "private" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= button_to 'Back', users_path, method: :get, class: "btn" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tr>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
      </tr>
    <% end %>
  </tbody>
    </tr>
</table>

<br>

<%= button_to 'New User', new_user_path, method: :get, class: "btn" %>
<%= button_to 'Log in', root_path, method: :get, class: "btn" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= button_to 'Back', users_path, method: :get, class: "btn" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @user.name %>'s profile</h1>
  

<% @user ||= current_user %>
<%= render 'tagged_skills', user: @user %>
<div class="footer">
	<% if @is_me %>
		<%= button_to 'Change user name', edit_user_path(@user) , method: :get, class: "btn" %>
		<%= button_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
	<% end %>
	<%= button_to 'Back', users_path , method: :get, class: "btn" %>
</div>