config/routes.rb
Rails.application.routes.draw do

  resources :tagged_skills,    :only => [:create, :destroy, :publish_skill, :hide_skill]
  resources :skill_plus,       :only => [:create, :destroy]
  resources :skills,           :only => [:index, :show, :create]
  resources :users            

  root 'application#root'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'publish_skill'  => 'tagged_skills#publish_skill'
  post   'hide_skill'     => 'tagged_skills#hide_skill'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :skill_plus,
		class_name: "SkillPlu",
		foreign_key: "skill_id",
		dependent: :destroy
	has_many :tagged_user,
		class_name: "TaggedSkill",
		foreign_key: "skill_id",
		dependent: :destroy
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    tss =  TaggedSkill.where(skill_id: @skill.id, state: "public")
    @tagged_user = User.where(id: tss.map(&:user_id))
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tr>

    <% @skills.each do |skill| %>
      <tr>
          <!-- <td><%= skill.id %></td> -->
          <td>
            <div class="skill"><%= link_to skill.name, skill %></div>
          </td>
      </tr>
    <% end %>
</table>

<br>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @skill.name %></h1>
  
<table class="table">
  <thead>
    <tr>
      <th colspan="3">Tagged Users</th>
    </tr>
  </thead>

    <tr>
  <tbody>
    <% @tagged_user.each do |tu| %>
      <tr>
        <td><%= link_to tu.name, tu %></td>
      </tr>
    <% end %>
  </tbody>
    </tr>
</table>


<%= button_to 'Back', skills_path , method: :get %>